blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability
    url: https://github.com/cre8/eudiplo/security/policy
    about: Please report security vulnerabilities via our security policy instead of creating a public issue
