services:
    eudiplo:
        image: ghcr.io/cre8/eudiplo:latest
        restart: always
        env_file:
            - .env
        ports:
            - '3000:3000'
        volumes:
            - ./config:/app/config

volumes:
    eudiplo-config:
        driver: local
