name: Build and push :latest Docker image

on:
    push:
        branches: ['main']

jobs:
    docker-latest:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              run:
                  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u
                  ${{ github.actor }} --password-stdin

            - name: Build and push latest image
              run: |
                  docker build -t ghcr.io/cre8/eudiplo:latest --build-arg VERSION=latest .
                  docker push ghcr.io/cre8/eudiplo:latest
